language = 'C++23'


name = 'GCC'
version = '14.2.0'

license = [{ name = 'GPLv3', url = 'https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Copying.html' }]


filename = 'Main.cpp'

object = 'a.out'


install = '''
#!/bin/bash
set -ue

sudo apt install -y g++-14

### Libraries
sudo apt install -y build-essential
cd /tmp

# Eigen
sudo apt install -y libeigen3-dev=3.4.0-2ubuntu2

# AtCoder Library
sudo mkdir /opt/ac-library/

wget https://github.com/atcoder/ac-library/releases/download/v1.5.1/ac-library.zip -O ac-library.zip
sudo unzip /tmp/ac-library.zip -d /opt/ac-library/

# GMP
wget https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz -O gmp-6.3.0.tar.xz
sudo tar -jxfv gmp-6.3.0.tar.xz

cd ./gmp-6.3.0/

./cofigure --prefix=/opt
make all
make install

cd ../

# Boost
wget https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.bz2 -O boost_1_86_0.tar.bz2
sudo tar -jxvf boost_1_86_0.tar.bz2

cd ./boost_1_86_0/

./bootstrap.sh --with-toolset=gcc --without-libraries=mpi,graph_parallel

build_args=(-j3 "toolset=gcc" "variant=release" "link=static" "runtime-link=static" "cxxflags=\"-std=gnu++23\"")
sudo ./b2 "${build_args[@]}" stage
sudo ./b2 "${build_args[@]}" --prefix=/opt/boost/gcc install
''' # 後から置換
compile = '''
#!/bin/bash
set -ue

ARGS=(
    "-std=gnu++23"

    -DONLINE_JUDGE
    -DATCODER

    -O2

    "-mtune=native"
    "-march=native"

    -Wall
    -Wextra
    -Wno-misleading-indentation

    "-fconstexpr-depth=2147483647"
    "-fconstexpr-loop-limit=2147483647"
    "-fconstexpr-ops-limit=2147483647"

    -I/opt/ac-library
    -I/opt/boost/gcc/include -L/opt/boost/gcc/lib
    -Igmpxx -lgmp
    -I/usr/include/eigen3
)

g++-14 "${ARGS[@]}"
''' # 後から置換

execution = [
    '''./a.out'''
]


### Libraries
[library.AC-Library]
    version = '1.5.1'
    licenses = [
        { name = 'CC0 1.0', url = 'https://github.com/atcoder/ac-library/blob/master/LICENSE' }
    ]

[library.Boost]
    version = '1.86.0'
    licenses = [
        { name = 'BSL 1.0', url = 'https://www.boost.org/LICENSE_1_0.txt' }
    ]

[library.GMP]
    version = '6.3.0'
    licenses = [
        { name = 'GNU LGPL v3', url = 'https://www.gnu.org/licenses/lgpl-3.0.html' },
        { name = 'GNU GPL v2', url = 'https://www.gnu.org/licenses/old-licenses/gpl-2.0.html' }
    ]

[library.Eigen]
    version = '3.4.0'
    licenses = [
        { name = 'MPL 2.0', url = 'https://www.mozilla.org/en-US/MPL/2.0/' },
    ]
